import { useState, useRef } from 'react';
import Head from 'next/head';
import {
  Box, 
  Typography, 
  TextField, 
  FormControl, 
  InputLabel, 
  Input, 
  FormHelperText
} from '@mui/material';
import {ISpaceship} from './components/Ship';

export default function SpaceshipsArmy() {
  const [generatedArmy, setGeneratedArmy] = useState<ISpaceship[]>([]);
  const [numberOfShipsTogenerate, setNumberOfShipsTogenerate] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  const createArmy = async () => {
    const response = await fetch(`/api/spaceships?numberOfShips=${numberOfShipsTogenerate}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const data = await response.json();
    console.log(data);
  }

  const handleNumberOfShipsChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const numberOfShips = Number(event.target.value);
    console.log(numberOfShips);
    setNumberOfShipsTogenerate(numberOfShips);
  }

  return (
    <Box>
      <Head>
        <title>Spaceships Battle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant='h1' fontSize='2rem'>Spaceshipson Army</Typography>
        <Box sx={{ width: '100%' }}>
          <Typography variant='h3' fontSize='1.6rem'>List</Typography>
          <form onSubmit={(e) => { 
            e.preventDefault(); 
            createArmy(); 
            // console.log('inputRef', inputRef.current?.value)
            }}>
            <FormControl>
              <InputLabel htmlFor="my-input">Number of ships</InputLabel>
              <Input id="my-input" aria-describedby="my-helper-text" placeholder='Enter the number of ships' onChange={handleNumberOfShipsChange} />
            </FormControl>
          </form>
        </Box>
      </main>

      <footer>
        Footer
      </footer>
    </Box>
  )
}
